<?xml version="1.0" encoding="UTF-8" ?>
<Package name="robots_advanced" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions />
    <Dialogs />
    <Resources>
        <File name="favicon" src="html/favicon.ico" />
        <File name="index" src="html/index.html" />
        <File name="bootstrap" src="html/css/bootstrap.css" />
        <File name="font" src="html/css/font.css" />
        <File name="modal" src="html/css/modal.css" />
        <File name="ng-table.min" src="html/css/ng-table.min.css" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.eot" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.svg" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.ttf" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.woff" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.eot" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.svg" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.ttf" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.woff" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.eot" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.svg" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.ttf" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.woff" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.eot" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.svg" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.ttf" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.woff" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.eot" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.svg" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.ttf" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.woff" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.eot" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.svg" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.ttf" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.woff" />
        <File name="glyphicons-halflings-regular" src="html/css/fonts/glyphicons-halflings-regular.eot" />
        <File name="glyphicons-halflings-regular" src="html/css/fonts/glyphicons-halflings-regular.svg" />
        <File name="glyphicons-halflings-regular" src="html/css/fonts/glyphicons-halflings-regular.ttf" />
        <File name="glyphicons-halflings-regular" src="html/css/fonts/glyphicons-halflings-regular.woff" />
        <File name="load-120px" src="html/img/load-120px.gif" />
        <File name="print" src="html/img/print.png" />
        <File name="reload" src="html/img/reload.png" />
        <File name="app" src="html/js/app.js" />
        <File name="config" src="html/js/config.js" />
        <File name="main" src="html/js/main.js" />
        <File name="homeController" src="html/js/core/controllers/homeController.js" />
        <File name="index" src="html/js/core/controllers/index.js" />
        <File name="module" src="html/js/core/controllers/module.js" />
        <File name="rootController" src="html/js/core/controllers/rootController.js" />
        <File name="directives" src="html/js/core/directives/directives.js" />
        <File name="index" src="html/js/core/directives/index.js" />
        <File name="module" src="html/js/core/directives/module.js" />
        <File name="filters" src="html/js/core/filters/filters.js" />
        <File name="index" src="html/js/core/filters/index.js" />
        <File name="module" src="html/js/core/filters/module.js" />
        <File name="index" src="html/js/core/services/index.js" />
        <File name="languageService" src="html/js/core/services/languageService.js" />
        <File name="module" src="html/js/core/services/module.js" />
        <File name="networkService" src="html/js/core/services/networkService.js" />
        <File name="prefService" src="html/js/core/services/prefService.js" />
        <File name="qimessagingService" src="html/js/core/services/qimessagingService.js" />
        <File name="settings" src="html/js/core/services/settings.js" />
        <File name="storeService" src="html/js/core/services/storeService.js" />
        <File name="systemService" src="html/js/core/services/systemService.js" />
        <File name="telepatheService" src="html/js/core/services/telepatheService.js" />
        <File name="core" src="html/js/states/core.js" />
        <File name="Chinese" src="html/languages/Chinese.json" />
        <File name="English" src="html/languages/English.json" />
        <File name="French" src="html/languages/French.json" />
        <File name="Japanese" src="html/languages/Japanese.json" />
        <File name="angular" src="html/lib/angular/angular.js" />
        <File name="angular.min" src="html/lib/angular/angular.min.js" />
        <File name="angular.min.js" src="html/lib/angular/angular.min.js.map" />
        <File name=".bower" src="html/lib/angular-bootstrap/.bower.json" />
        <File name="bower" src="html/lib/angular-bootstrap/bower.json" />
        <File name="ui-bootstrap-tpls" src="html/lib/angular-bootstrap/ui-bootstrap-tpls.js" />
        <File name="ui-bootstrap-tpls.min" src="html/lib/angular-bootstrap/ui-bootstrap-tpls.min.js" />
        <File name="ui-bootstrap" src="html/lib/angular-bootstrap/ui-bootstrap.js" />
        <File name="ui-bootstrap.min" src="html/lib/angular-bootstrap/ui-bootstrap.min.js" />
        <File name="angular-resource" src="html/lib/angular-resource/angular-resource.js" />
        <File name="angular-resource.min" src="html/lib/angular-resource/angular-resource.min.js" />
        <File name="angular-resource.min.js" src="html/lib/angular-resource/angular-resource.min.js.map" />
        <File name="angular-sanitize" src="html/lib/angular-sanitize/angular-sanitize.js" />
        <File name="angular-sanitize.min" src="html/lib/angular-sanitize/angular-sanitize.min.js" />
        <File name="angular-sanitize.min.js" src="html/lib/angular-sanitize/angular-sanitize.min.js.map" />
        <File name=".bower" src="html/lib/angular-touch/.bower.json" />
        <File name="angular-touch" src="html/lib/angular-touch/angular-touch.js" />
        <File name="angular-touch.min" src="html/lib/angular-touch/angular-touch.min.js" />
        <File name="angular-touch.min.js" src="html/lib/angular-touch/angular-touch.min.js.map" />
        <File name="bower" src="html/lib/angular-touch/bower.json" />
        <File name="README" src="html/lib/angular-touch/README.md" />
        <File name=".bower" src="html/lib/angular-translate/.bower.json" />
        <File name="angular-translate" src="html/lib/angular-translate/angular-translate.js" />
        <File name="angular-translate.min" src="html/lib/angular-translate/angular-translate.min.js" />
        <File name="bower" src="html/lib/angular-translate/bower.json" />
        <File name="README" src="html/lib/angular-translate/README.md" />
        <File name="angular-translate-handler-log" src="html/lib/angular-translate/angular-translate-handler-log/angular-translate-handler-log.js" />
        <File name="angular-translate-handler-log.min" src="html/lib/angular-translate/angular-translate-handler-log/angular-translate-handler-log.min.js" />
        <File name="angular-translate-interpolation-messageformat" src="html/lib/angular-translate/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat.js" />
        <File name="angular-translate-interpolation-messageformat.min" src="html/lib/angular-translate/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat.min.js" />
        <File name="angular-translate-loader-partial" src="html/lib/angular-translate/angular-translate-loader-partial/angular-translate-loader-partial.js" />
        <File name="angular-translate-loader-partial.min" src="html/lib/angular-translate/angular-translate-loader-partial/angular-translate-loader-partial.min.js" />
        <File name="angular-translate-loader-static-files" src="html/lib/angular-translate/angular-translate-loader-static-files/angular-translate-loader-static-files.js" />
        <File name="angular-translate-loader-static-files.min" src="html/lib/angular-translate/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js" />
        <File name="angular-translate-loader-url" src="html/lib/angular-translate/angular-translate-loader-url/angular-translate-loader-url.js" />
        <File name="angular-translate-loader-url.min" src="html/lib/angular-translate/angular-translate-loader-url/angular-translate-loader-url.min.js" />
        <File name="angular-translate-storage-cookie" src="html/lib/angular-translate/angular-translate-storage-cookie/angular-translate-storage-cookie.js" />
        <File name="angular-translate-storage-cookie.min" src="html/lib/angular-translate/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js" />
        <File name="angular-translate-storage-local" src="html/lib/angular-translate/angular-translate-storage-local/angular-translate-storage-local.js" />
        <File name="angular-translate-storage-local.min" src="html/lib/angular-translate/angular-translate-storage-local/angular-translate-storage-local.min.js" />
        <File name="angular-ui-router" src="html/lib/angular-ui-router/angular-ui-router.js" />
        <File name="angular-ui-router.min" src="html/lib/angular-ui-router/angular-ui-router.min.js" />
        <File name="jquery-migrate" src="html/lib/jquery/jquery-migrate.js" />
        <File name="jquery-migrate.min" src="html/lib/jquery/jquery-migrate.min.js" />
        <File name="jquery" src="html/lib/jquery/jquery.js" />
        <File name="jquery.min" src="html/lib/jquery/jquery.min.js" />
        <File name="jquery.min" src="html/lib/jquery/jquery.min.map" />
        <File name=".bower" src="html/lib/ng-table/.bower.json" />
        <File name="" src="html/lib/ng-table/.bowerrc" />
        <File name="" src="html/lib/ng-table/.editorconfig" />
        <File name="" src="html/lib/ng-table/.gitignore" />
        <File name="" src="html/lib/ng-table/.jshintrc" />
        <File name=".travis" src="html/lib/ng-table/.travis.yml" />
        <File name="bower" src="html/lib/ng-table/bower.json" />
        <File name="CONTRIBUTING" src="html/lib/ng-table/CONTRIBUTING.md" />
        <File name="Gruntfile" src="html/lib/ng-table/Gruntfile.js" />
        <File name="karma.conf" src="html/lib/ng-table/karma.conf.js" />
        <File name="LICENSE" src="html/lib/ng-table/LICENSE" />
        <File name="ng-table" src="html/lib/ng-table/ng-table.css" />
        <File name="ng-table" src="html/lib/ng-table/ng-table.js" />
        <File name="ng-table" src="html/lib/ng-table/ng-table.less" />
        <File name="ng-table" src="html/lib/ng-table/ng-table.map" />
        <File name="ng-table.min" src="html/lib/ng-table/ng-table.min.css" />
        <File name="ng-table.min" src="html/lib/ng-table/ng-table.min.js" />
        <File name="package" src="html/lib/ng-table/package.json" />
        <File name="README" src="html/lib/ng-table/README.md" />
        <File name="tableControllerSpec" src="html/lib/ng-table/test/tableControllerSpec.js" />
        <File name="tableParamsSpec" src="html/lib/ng-table/test/tableParamsSpec.js" />
        <File name="tableSpec" src="html/lib/ng-table/test/tableSpec.js" />
        <File name="ocLazyLoad" src="html/lib/ocLazyLoad/ocLazyLoad.js" />
        <File name="ocLazyLoad.min" src="html/lib/ocLazyLoad/ocLazyLoad.min.js" />
        <File name="require" src="html/lib/requirejs/require.js" />
        <File name="testBaseUrl" src="html/lib/requirejs/testBaseUrl.js" />
        <File name="ct-ui-router-extras" src="html/lib/ui-router-extras/ct-ui-router-extras.js" />
        <File name="ct-ui-router-extras.min" src="html/lib/ui-router-extras/ct-ui-router-extras.min.js" />
        <File name="base" src="html/modules/hardware/css/base.css" />
        <File name="states" src="html/modules/hardware/js/states.js" />
        <File name="hardwareController" src="html/modules/hardware/js/controllers/hardwareController.js" />
        <File name="index" src="html/modules/hardware/js/controllers/index.js" />
        <File name="module" src="html/modules/hardware/js/controllers/module.js" />
        <File name="Chinese" src="html/modules/hardware/lang/Chinese.json" />
        <File name="English" src="html/modules/hardware/lang/English.json" />
        <File name="French" src="html/modules/hardware/lang/French.json" />
        <File name="Japanese" src="html/modules/hardware/lang/Japanese.json" />
        <File name="base" src="html/modules/hardware/partials/base.html" />
        <File name="base" src="html/modules/memory/css/base.css" />
        <File name="states" src="html/modules/memory/js/states.js" />
        <File name="index" src="html/modules/memory/js/controllers/index.js" />
        <File name="memoryController" src="html/modules/memory/js/controllers/memoryController.js" />
        <File name="module" src="html/modules/memory/js/controllers/module.js" />
        <File name="Chinese" src="html/modules/memory/lang/Chinese.json" />
        <File name="English" src="html/modules/memory/lang/English.json" />
        <File name="French" src="html/modules/memory/lang/French.json" />
        <File name="Japanese" src="html/modules/memory/lang/Japanese.json" />
        <File name="base" src="html/modules/memory/partials/base.html" />
        <File name="base" src="html/modules/settings/css/base.css" />
        <File name="states" src="html/modules/settings/js/states.js" />
        <File name="index" src="html/modules/settings/js/controllers/index.js" />
        <File name="module" src="html/modules/settings/js/controllers/module.js" />
        <File name="settingsController" src="html/modules/settings/js/controllers/settingsController.js" />
        <File name="Chinese" src="html/modules/settings/lang/Chinese.json" />
        <File name="English" src="html/modules/settings/lang/English.json" />
        <File name="French" src="html/modules/settings/lang/French.json" />
        <File name="Japanese" src="html/modules/settings/lang/Japanese.json" />
        <File name="base" src="html/modules/settings/partials/base.html" />
        <File name="base" src="html/modules/tethering/css/base.css" />
        <File name="states" src="html/modules/tethering/js/states.js" />
        <File name="index" src="html/modules/tethering/js/controllers/index.js" />
        <File name="module" src="html/modules/tethering/js/controllers/module.js" />
        <File name="tetheringController" src="html/modules/tethering/js/controllers/tetheringController.js" />
        <File name="Chinese" src="html/modules/tethering/lang/Chinese.json" />
        <File name="English" src="html/modules/tethering/lang/English.json" />
        <File name="French" src="html/modules/tethering/lang/French.json" />
        <File name="Japanese" src="html/modules/tethering/lang/Japanese.json" />
        <File name="base" src="html/modules/tethering/partials/base.html" />
        <File name="base" src="html/partials/app/base.html" />
        <File name="home" src="html/partials/app/home.html" />
        <File name="password-classic" src="html/partials/directives/password-classic.html" />
        <File name="text-classic" src="html/partials/directives/text-classic.html" />
        <File name="askTethering" src="html/partials/modal/askTethering.html" />
        <File name="permitDeactivation" src="html/partials/modal/permitDeactivation.html" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
